install: make install
cache:
- directories:
  - "$TRAVIS_BUILD_DIR/.terraform"
  - "$HOME/terraform"
script: make plan
deploy:
- provider: script
  skip_cleanup: true
  script: export ENV=staging; make terraform apply
  on:
    branch: master
- provider: script
  skip_cleanup: true
  script: export ENV=production; make terraform apply
  on:
    branch: /^v[0-9]+\.[0-9]+\.[0-9]+$/
