# We require the sudo command
sudo: required
# Cache the Terraform binary and our local state after each build
cache:
- directories:
  - "$HOME/terraform"
# Run make install command to fetch Terraform binary
install: make install-terraform
# Run Terraform plan
script: terraform plan -var fastly_api_token=$FASTLY_API_TOKEN ./terraform
